#!groovy

// Generated by IBM TransformationAdvisor
// Tue Feb 19 15:46:46 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresortswar'
    mvnCommands = '--version'
    test='false'
}